fail_fast: false
repos:
-   repo: local
    hooks:
    -   id: mix-lint
        name: 'elixir: lint'
        entry: make lint
        language: system
        files: \.ex$
    -   id: mix-dialyzer
        name: 'elixir: dialyzer'
        entry: make dialyzer
        language: system
        files: \.ex$
    -   id: mix-test
        name: 'elixir: test'
        entry: make test-ci
        language: system
        files: \.ex$
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: master
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: check-symlinks
    -   id: detect-private-key
