-   repo: local
    hooks:
    -   id: mix-test
        name: 'elixir: mixing tests'
        entry: mix test
        language: system
        files: \.ex$
    -   id: mix-test
        name: 'elixir: mixing compile'
        entry: mix compile
        language: system
        files: \.ex$
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: master
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: check-symlinks
    -   id: detect-private-key
