version: '3'

services:
  web:
    build: .
    command: mix phx.server
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    depends_on:
      - db
  db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
